/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse File Endpoint */
        post: operations["parse_file_endpoint_api_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetch-jd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch Jd Endpoint */
        post: operations["fetch_jd_endpoint_api_fetch_jd_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Endpoint */
        post: operations["analyze_endpoint_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Resume Text
             * @description The candidate's resume as plain text
             */
            resume_text: string;
            /**
             * Jd Text
             * @description The job description as plain text
             */
            jd_text: string;
        };
        /** Body_parse_file_endpoint_api_parse_post */
        Body_parse_file_endpoint_api_parse_post: {
            /** File */
            file: string;
        };
        /**
         * ErrorDetail
         * @description Standard error shape for non-2xx responses.
         */
        ErrorDetail: {
            /**
             * Error
             * @description Machine-readable error code
             */
            error: string;
            /**
             * Message
             * @description Human-readable explanation
             */
            message: string;
            /**
             * Detail
             * @description Additional context, e.g. parser library error
             */
            detail?: string | null;
        };
        /**
         * FetchJDMetadata
         * @description Information about a fetched URL.
         */
        FetchJDMetadata: {
            /**
             * Source Url
             * @description The URL that was fetched (after redirects)
             */
            source_url: string;
            /**
             * Source Domain
             * @description Just the hostname, useful for UI display
             */
            source_domain: string;
            /**
             * Title
             * @description Detected page title
             */
            title?: string | null;
            /** Char Count */
            char_count: number;
        };
        /**
         * FetchJDRequest
         * @description Request body for /api/fetch-jd.
         */
        FetchJDRequest: {
            /**
             * Url
             * @description The JD page URL to fetch
             */
            url: string;
        };
        /**
         * FetchJDResponse
         * @description Successful fetch — extracted JD text plus metadata plus any warnings.
         */
        FetchJDResponse: {
            /** Text */
            text: string;
            metadata: components["schemas"]["FetchJDMetadata"];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["FetchWarning"][];
        };
        /**
         * FetchWarning
         * @description Non-fatal issues encountered during URL fetching.
         * @enum {string}
         */
        FetchWarning: "low_content" | "no_title_found" | "possible_partial";
        /**
         * FileKind
         * @description The kinds of files we know how to parse.
         * @enum {string}
         */
        FileKind: "pdf" | "docx" | "txt" | "md" | "tex";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Model */
            model: string;
        };
        /**
         * ParseMetadata
         * @description Information about what was parsed, separate from the text itself.
         */
        ParseMetadata: {
            kind: components["schemas"]["FileKind"];
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Page Count
             * @description Pages for PDFs/DOCX, None for plain text
             */
            page_count?: number | null;
            /** Char Count */
            char_count: number;
        };
        /**
         * ParseResponse
         * @description Successful parse — text plus metadata plus any warnings.
         */
        ParseResponse: {
            /** Text */
            text: string;
            metadata: components["schemas"]["ParseMetadata"];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ParseWarning"][];
        };
        /**
         * ParseWarning
         * @description Non-fatal issues the caller should know about.
         * @enum {string}
         */
        ParseWarning: "low_text_density" | "partial_extraction" | "encrypted_but_readable";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    parse_file_endpoint_api_parse_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_file_endpoint_api_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Unsupported file type, encrypted PDF, or scanned PDF */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description File could not be parsed (corrupted) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    fetch_jd_endpoint_api_fetch_jd_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchJDRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchJDResponse"];
                };
            };
            /** @description Invalid URL */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Site bot-blocked or extraction failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Network or upstream HTTP error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Upstream timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    analyze_endpoint_api_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
